### ISSUE TITLE
Q: Run from deployment machine?

### ISSUE THREAD

**Issue by jrochkind** [capistrano/maintenance#43]
I have a cronjob that needs to do some downtime work, I'd love if it were able to wrap itself the maintenance:enable and disable tasks, using the same logic ordinarily used for turning on maintenance mode 'manually', to keep things DRY and consistent. 

I guess I'd have to add cap and cap plugins to the `production` gem group... and then just have my cron job actually run `bundle exec cap maintenance:enable` from the production machine itself? I guess it would still be ssh'ing, even though it's on the same machine it's ssh'ing too, so would have to make sure to set up ssh keys for localhost login. I guess?

Does this make any sense at all? Is it a terrible idea? Is there any better way to do this?

Thanks for any advice!

**Comment by mattbrictson** [comment]
I understand the desire to keep things DRY, but doing it via this gem is not a good idea IMHO.

I would probably write a shell script to do the stuff `capistrano-maintenance` does, and then call that script via cron or via a trivial capistrano task.

---

GitHub issues are for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).

**Comment by jrochkind** [comment]
thanks for the advice!
